### PR TITLE
Polygon: black stroke added by default. Still missing props

### PR DESCRIPTION
**Pull request by mbarrenechea**
This PR gives you the possibility of adding strokes to polygons. Right now this stroke is black by default. I need to change also globe.gl to allow more properties like `polygonStrokeColor`. Probably you could help me with this @vasturiano 

What I did here is quite simple. Inside the polygon layer file, I created a Three Group. A Mesh (like before) and a Line will be added to this Group. For generating the stroke geometry I'm using `src/utils/coordLineTranslate.js`. All of this code it's just a copy from drawThreeGeo

The result => 
image

It would be nice if we can add `polygonStrokeColor` to https://github.com/vasturiano/globe.gl and https://github.com/vasturiano/react-globe.gl

Let me know if you have some doubts or if I can help you somehow @vasturiano

### CODE REVIEW

**Comment by vasturiano** [comment]
Thanks for initiating this PR @mbarrenechea!

I think from an API design standpoint, this feature would be the most useful by surfacing two component props:
* `polygonStrokeWidth`: Ideally, this width would be set in terms of globe great circle degrees. But, I'm aware that adding custom widths to [Line](https://threejs.org/docs/#api/en/objects/Line) objects is far from trivial. So, it may be easier to define this prop as a boolean instead, and rename it to say `polygonIncludeStroke` (default to `false` for backwards compatibility).
* `polygonStrokeColor`: the stroke color, ideally supporting transparency, via `rgba` values. Just like `polygonCapColor` for example. It could simply default to `'black'` if no value is set.

I'm also thinking that may be more suiting to add this stroke functionality to this repo instead:
https://github.com/vasturiano/three-conic-polygon-geometry
That would simplify things a fair amount, and also make stroke features available to other consumers of that module. What do you think?

**Comment by mbarrenechea** [comment]
@vasturiano I agree with your points. You know better how everything is structured, feel free to update it.

Thank you!!!!

**Comment by vasturiano** [comment]
Functionality merged. There's a single new prop called `polygonStrokeColor`. If left `undefined` no stroke is added.
Example here: https://vasturiano.github.io/three-globe/example/country-polygons/

Thanks again for kick-starting this PR, it's a nice feature. 👍

**Comment by raganowicz** [comment]
@vasturiano I see that polygonStrokeWidth hasn't been implemented in the API? Is there any way to increase the polygon stroke width?

**Comment by vasturiano** [comment]
@raganowicz that's right, that prop doesn't exist. Please see above for the reasons why. Essentially thick lines remain problematic in WebGL, and far from trivial to implement. Normally you have to do it with a mesh, which dramatically increases the complexity of the geometries, and affects rendering performance.

**Pull request merged**
