### PR TITLE
The ability to specify the number of the dot marker segments and change the altitude of the start/end points of the Arc

### PR DESCRIPTION
**Pull request by ElviraKukhtaruk**
### Problem 1:

The number of `labelDot` segments is fixed (16).

### Solution:

Added `labelDotSegments` function to change the default (16) labelDot number of segments:

```
const Globe = new ThreeGlobe()
        .labelSize('size')
        .labelDotRadius(2)
        .labelColor('color')
        .labelDotSegments(32)
```
Also, `rollup` import assertions (the `assert` keyword) have been removed from node starting in v22.0.0. Using `with` instead.

###  Problem 2:

I had some problems with Arc layer when using `polygonsData` method with `polygonAltitude` set to `0.01` and `labelsData` with `labelAltitude` set to `0.011` because the start/end points of the Arc were under the polygons layer so two label points were not 'connected' with Arc.
At small distances, the arc is not even visible.

**Example**
Arc between Frankfurt and Prague:
```
 let arc = [{
      startLat: 50.1008, startLng: 14.26,
      endLat: 50.033333, endLng: 8.570556
 }];
 globe
    .polygonAltitude(0.01)
    .labelsData(...)
    .labelText(...)
    .labelAltitude(0.011)
    .arcsData(arc)
```
screenshot_2024-07-03-111508

### Solution:

I added the ability to change the altitude of the start/end points of the Arc:
```
let arc = [{
       startLat: ..., startLng: ..., startAlt: 0.011,
       endLat: ..., endLng: ..., endAlt: 0.011
}];
const Globe = new ThreeGlobe()
      .arcsData(arc)
```
**Example**
```
globe
    .polygonAltitude(0.01)
    .labelsData(...)
    .labelText(...)
    .labelAltitude(0.011)
    .arcsData(arc)
    .arcStartAlt(0.011)
    .arcEndAlt(0.011)
```
screenshot_2024-07-03-111733

I added these lines of code so that when the arcStartAlt/arcEndAlt is not set, it defaults to 0. Then the existing code will not "break" if the arcStartAlt/arcEndAlt is not set (src/layers/arcs.js):
```
  // Set default altitude
  if(!curveD.startAlt) curveD.startAlt = 0;
  if(!curveD.endAlt) curveD.endAlt = 0;
```

### CODE REVIEW

**Comment by vasturiano** [comment]
@ElviraKukhtaruk thanks for reaching out.

The idea of the arcs is that they always start and end in the globe's surface. But you can set how high the go in between using the `arcAltitude` prop. Does that not work for your case?

Regarding the resolution of the label dots, could you elaborate a bit more the reason why that's needed? Do you want it to have higher or lower resolution?

And about the `with` in the import statements of the bundler, that's still a rather new keyword that is not understood in older versions of node. So it would force a node version upgrade which is undesirable. `assert` might be deprecated but it's supported by all versions thus far.

**Comment by ElviraKukhtaruk** [comment]
> @ElviraKukhtaruk thanks for reaching out.
> 
> The idea of the arcs is that they always start and end in the globe's surface. But you can set how high the go in between using the `arcAltitude` prop. Does that not work for your case?
> 
> Regarding the resolution of the label dots, could you elaborate a bit more the reason why that's needed? Do you want it to have higher or lower resolution?
> 
> And about the `with` in the import statements of the bundler, that's still a rather new keyword that is not understood in older versions of node. So it would force a node version upgrade which is undesirable. `assert` might be deprecated but it's supported by all versions thus far.

When using the `labelsData` method with `labelAltitude` set to `0.011` (example), setting `arcAltitude` to `0.011` doesn't work as expected. The result is an arc that is positioned higher, but it also changes the shape, making it more pointed and elongated.

In my case, it would be helpful to have the option to adjust the resolution of the label dots, as I need them to be in higher resolution. I believe others may also find this option useful for their own use cases.

Regarding the use of with in the `import` statements of the bundler, I agree with your point.

**Comment by ElviraKukhtaruk** [comment]
@vasturiano,
I was considering using the `paths layer`, but in my case, it's better to use a line with an altitude curve rather than a straight line.

At the moment, I'm using 32 segments for my dots to achieve a more perfect circle.

**Comment by vasturiano** [comment]
@ElviraKukhtaruk I've just increased the default resolution of the dots to `32`. I think for the sake of api simplicity it doesn't warrant a dedicated prop in the module.

Regarding the arcs layer it's better to stick with the concept of them starting/ending on the ground. For your case you can always set an altitude to the curve which would solve your issue. For more sophisticated cases there's always the paths layer which lets you connect any coordinates in space, even simulating a curve by adding interpolated points in between.

**Pull request closed without merging**
